//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailtemplate
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string stagingsubject { get; set; }
        public string stagingbody { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> ModifierID { get; set; }
        public Nullable<System.DateTime> published { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> isactived { get; set; }
        public Nullable<int> categoryID { get; set; }
    }
}
