//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class learningissue
    {
        public int id { get; set; }
        public string issue { get; set; }
        public Nullable<int> researchonly { get; set; }
        public Nullable<int> orderitem { get; set; }
        public Nullable<int> iscurrent { get; set; }
    }
}
