//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string path { get; set; }
        public string filename { get; set; }
        public Nullable<int> modifierID { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string description { get; set; }
        public string text { get; set; }
        public string cssID { get; set; }
        public Nullable<int> isactive { get; set; }
    }
}
