//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class program
    {
        public int id { get; set; }
        public string name { get; set; }
        public string days { get; set; }
        public Nullable<int> numOfWeeks { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> maximum { get; set; }
        public Nullable<int> cutoff { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> creatorId { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> modifierId { get; set; }
        public Nullable<System.DateTime> archived { get; set; }
        public Nullable<int> archiverId { get; set; }
        public Nullable<int> reminder_num { get; set; }
        public Nullable<int> reminder_sent { get; set; }
    }
}
