//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int id { get; set; }
        public System.DateTime starting { get; set; }
        public System.DateTime ending { get; set; }
        public string campus { get; set; }
        public int lecturer { get; set; }
        public int type { get; set; }
        public System.DateTime created { get; set; }
        public int creatorId { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> modifierId { get; set; }
        public Nullable<System.DateTime> archived { get; set; }
        public Nullable<int> archiverID { get; set; }
    }
}
