//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class waiting
    {
        public int id { get; set; }
        public string studentID { get; set; }
        public int sessionId { get; set; }
        public string assisstance { get; set; }
        public string reason { get; set; }
        public int priority { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> creatorId { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> modifierId { get; set; }
        public Nullable<System.DateTime> archived { get; set; }
        public Nullable<int> archiverID { get; set; }
        public Nullable<int> isgroup { get; set; }
        public string numpeople { get; set; }
        public string assigntype { get; set; }
        public string assigntypeOther { get; set; }
        public string subject { get; set; }
        public string appointments { get; set; }
        public string appointmentsOther { get; set; }
        public string assisstanceText { get; set; }
    }
}
